### PR TITLE
Fix recipes

### LINKED ISSUE #57: Missing recipe for brass, invar and bronze ingot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

There are no recipes for these ingots

### To Reproduce

.

### Expected behavior

.

### Logs & Environment

_No response_

### Screenshots & Video

_No response_

### PR DESCRIPTION
**Pull request by Edivad99**
This PR fix:
- Close #57 
- A duplication between "Slug Dust" and "Ground Blast Furnace Slag", (they had different names but the same purpose)

### CODE REVIEW

File: src/main/java/mods/railcraft/data/recipes/RailcraftRecipeProvider.java [hunk 1]
```diff
@@ -1394,19 +1395,52 @@ private void buildBlockStorageRecipes(Consumer<FinishedRecipe> consumer) {
...
+    ShapedRecipeBuilder.shaped(RailcraftItems.INVAR_INGOT.get(), 3)
+        .pattern("ab")
+        .pattern("b ")
+        .define('a', RailcraftTags.Items.NICKEL_INGOT)
+        .define('b', Tags.Items.INGOTS_IRON)
+        .unlockedBy(getHasName(RailcraftItems.NICKEL_INGOT.get()),
+            has(RailcraftItems.NICKEL_INGOT.get()))
+        .unlockedBy(getHasName(Items.IRON_INGOT),
+            has(Items.IRON_INGOT))
+        .save(consumer, new ResourceLocation(Railcraft.ID, "nickel_ingot_crafted_with_ingots"));
```
Comment (Edivad99) [inline src/main/java/mods/railcraft/data/recipes/RailcraftRecipeProvider.java]: Fix it’s invar ingot

**Comment by Edivad99** [comment]
Ready to be merge
