### PR TITLE
Train/Cart dispenser

### LINKED ISSUE #47: PhantomMinecartSlot sometimes consumes the item in hand
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

- PhantomMinecartSlot sometimes consumes the item in hand.
- If you have more than 1 item in your inventory, the wrong item is placed

### To Reproduce

.

### Expected behavior

.

### Logs & Environment

_No response_

### Screenshots & Video

_No response_

### PR DESCRIPTION
**Pull request by Edivad99**
close #47

### CODE REVIEW

File: src/main/java/mods/railcraft/data/RailcraftLanguageProvider.java [hunk 1]
```diff
@@ -440,6 +448,7 @@ private void tipsTranslations() {
     this.add(Translations.Tips.HIT_CROWBAR_TO_CHANGE_MODE, "- Hit with Crowbar to change mode -");
     this.add(Translations.Tips.HIT_CROWBAR_TO_CHANGE_FORCE, "- Hit with Crowbar to change force -");
     this.add(Translations.Tips.HIT_CROWBAR_TO_ROTATE, "- Hit with Crowbar to rotate -");
+    this.add(Translations.Tips.PAIR_WITH_CONTROL_TRACK, "- Pair with Control track-");
```
Comment (Edivad99) [inline src/main/java/mods/railcraft/data/RailcraftLanguageProvider.java]: Add space
