### PR TITLE
Fixes #301: Token signals become disconnected on world reload

### LINKED ISSUE #301: Token signals become disconnected on world reload
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the Bug

Token signals forming a token area become disconnected on world reload. 

### Railcraft Reborn version

1.1.9

### NeoForge/Forge version

NeoForge 47.1.101

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Place down any number of token signals
2. Link them into a token area
3. Leave and rejoin the world, or restart the server

### Expected behavior

The token signals should remain connected in a token area

### Logs & Environment

```Shell

```

### Screenshots & Video

https://github.com/user-attachments/assets/6c5b50e1-f36d-406d-8b84-099ae569dea6

### PR DESCRIPTION
**Pull request by tongkl1**
* Updating ringId doesn't trigger BlockEntity.setChanged(), therefore the change is not persisted across world reload.
* isOrphaned incorrently purges any token ring with unloaded token signals.

### CODE REVIEW

File: src/main/java/mods/railcraft/world/signal/SimpleTokenRing.java [hunk 1]
```diff
@@ -95,7 +95,15 @@ public void tick() {
...
-    return !this.peers.stream().map(this::peerAt).allMatch(Optional::isPresent);
+    return this.peers.stream().allMatch(this::isNotTokenSignalEntity);
+  }
+
+  boolean isNotTokenSignalEntity(BlockPos blockPos) {
+    if (!this.level.isLoaded(blockPos)) {
+      return false;
+    }
+    var blockEntity = this.level.getBlockEntity(blockPos);
+    return !(blockEntity instanceof TokenSignalEntity tokenSignal) || blockEntity.isRemoved();
```
Comment (Edivad99) [inline src/main/java/mods/railcraft/world/signal/SimpleTokenRing.java]:
```suggestion
    return !(blockEntity instanceof TokenSignalEntity) || blockEntity.isRemoved();
```

**Comment by Edivad99** [comment]
Can you also open a PR for 1.21.x?
